dist: bionic

language: php

# Define the php versions against we want to test our code
php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

env:
  matrix:
    - COMPOSER_FLAGS="--prefer-lowest"
    - COMPOSER_FLAGS=""

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --no-suggest

# Note: Code coverage requires php-xDebug extension enabled on CI server
script:
  - composer test -- --coverage-clover=coverage.xml

#after_script:

after_success:
  # Submit coverage report to https://codecov.io
  - bash <(curl -s https://codecov.io/bash)

#after_failure:

# Monitor only these branches
branches:
  only:
    - master
    - dev

# You can force delete the cache using travis-ci web interface
cache:
  directories:
    - $HOME/.composer/cache
