name: tests

on:
  push:
    branches:
      - master
      - dev
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.1, 7.2, 7.3, 7.4]
        composer-flag: [prefer-lowest, prefer-stable]

    name: php v${{ matrix.php }} - ${{ matrix.composer-flag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: php-v${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: php-v${{ matrix.php }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: xdebug

      - name: Install dependencies
        run: composer update --${{ matrix.composer-flag }} --no-interaction

      - name: Execute tests
        run: composer test -- --coverage-clover=coverage.xml

      - name: Submit code coverage
        run: bash <(curl -s https://codecov.io/bash)
